project_name: vault-plugin-secrets-gitlab
release:
  gitlab:
    owner: splunk
    name: vault-plugin-secrets-gitlab
before:
  hooks:
    - go mod download
github_urls:
  api: https://github.com/api/v3/
  download: https://github.com
  # set to true if you use a self-signed certificate
  skip_tls_verify: false
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
